insert into logros values
	("¡Somos Exterminadores de Buhos!","Mata 5 hipopogrifos"),
	("¡A la rica ensalada!","Mata 10 Osolechuga"),
	("¡El destructor de memes!","Derrota a Javier Ramos, Horse Luis, Rafalillo y Troll"),
	("¡No te tima ni Dios!","Derrota a 10 vendedores de seguros"),
	("¡Welcome to Jurassic Park!","Derrota a 15 Velociraptores"),
	("¡El terror de la Tercera Edad!","Derrota a 10 jubilados"),
	("¡Vamos al Circo!","Elimina 15 Payasos"),
	("¿Tengo que ponerme la Anti-tetanica?","Elimina 20 Murciegalos"),
	("¡Maestro Pomekon!","Derrota a 10 Pichakus"),
	("¡El defensor de los derechos Homosexuales!","Huir de Mari-Conan"),
	("¡Solo 5 minutitos mas!","Derrota al Reloj Despertador"),
	("¡El engatusador de perros!","Derrota 15 lobos terribles"),
	("¡Hackerman!","Derrota a Anti-captcha"),
	("¡El retrovirus!","Derrota a Enemigo Pixelado"),
	("¡El señor este contigo!","Derrota 5 Surfistas Catolicos y 5 Testigos de Jehova"),
	("¡Peluquero¡","Derrota 5 elementales de Pelos"),
	("¡No la mires a los ojos!","Derrota a 3 Medusas"),
	("¿No es una fieshta?","Derrota a 3 Salamanquesas"),
	("¡Por favor una mascara anti-gas!","Derrota a 5 elementales de cuesco"),
	("¡Nos comen los chinos!","Derrota 3 Ninjas con Pandereta"),
	("¡SuhrManito!","Derrota 5 Canis"),
	("¡Esto no es Blizzard!","Derrota una horda Zergling, como minimo 20"),
	("¿Pero como aguantas eso?","Derrota 5 Cruzcampos"),
	("¡Experto en pelis de serie B!","Derrota 15 Crocopulpos"),
	("¡Y vuelve a salir pifia!","Derrota 3 Dados Maldito"),
	("¡Casi lo consigues!","Derrota 3 Suspensos por un 4,5"),
	("¡Salvador de la Media Tierra","Derrota a el Señor Obstuso"),
	("¡Accion de Gracias!","Derrota al Gallo Colosal"),
	("¡Experto Programador!","Derrota 10 JavaExceptions"),
	("¿Quieres pan?","Derrota 15 Golems de masa de pan"),
	("¡New game plus!","Termina el juego"),
	("¡Beserkre!","Solo usa el boton atacar"),
	("¡Te han guanteado el jocico!","Te eliminan en la partida"),
	("¡Ansia viva!","Llega al 5º nivel"),
	("¡Cansaliebres!","Llega al 7º nivel"),
	("¡Jarto Sopas!","Llega al 10º nivel"),
	("¡Zoofobico!","Derrota a todos los monstruos animales"),
	("¡Amante de lo retro!","Has encontrado a BOO"),
	("¡Lo juro, fue sin querer!","Morir en el 1º nivel"),
	("¡Has malgastado tu vida!","Morir contra el jefe final"),
	("¡Dedicate a algo mejor!","Sal del juego"),
	("¡Crugiendo lomos!","Usa 'La Vara' contra un enemigo"),
	("¡BFF!","Derrota a Rafalillo 3 veces"),
	("¿Sobres? ¿Qué sobres?","Derrota a 'El Bastardo'"),
	("¡Por fuera hueles mal, pero por dentro... Qué peste..!","Derrota 10 Babosas Gigantes"),
	("¡Eres una belleza!","Derrota a Horse Luis"),
	("¡Puedes pedir un deseo!","Aparece Javier Ramos"),
	("¡Los Fampiros existen!","Derrota a Fampiro"),
	("¡El ejercito de las tinieblas!","Derrota 20 Muertos Vivientes"),
	("¿Tengo que comer verdura?","Derrota a Brocoli"),
	("¡Muerte por kiki!","Eres derrotado por una amazona"),
	("¡El jardinero de bricomania!","Derrota a 20 enredaderas"),
	("¡Experto en Foros!","Derrota 3 trolls"),
	("¡Pa' loca tu calva!","Derrota a Mari-Conan");