insert into arma values
("Guante", "fuerza", 1, "Un guante que protege tu mano cuando guanteas enemigos.",1),
("Corchopan", "fuerza", 1, "Cilindro de material esponjoso que no vale para nada.",2),
("Puñao de piedras", "destreza", 1, "Sirven para mantener el enemigo a distancia.",1),
("Frisbi", "destreza", 1, "Disco de plástico que vuela pero tampoco mucho...",2),
("Palillo chino", "intelecto", 1, "Un palillo de la comida china que usas cómo varita mágica",1),
("Rotulador", "intelecto", 1, "Puedes anotar cosas con él, pero también usarlo cómo varita.",2),
("Estaca", "fuerza", 2, "Hecha con madera de membrillo que, aunque dobla, hinca.",3),
("Tarama de olivo", "fuerza", 2, "Rama sobrante de la poda, escuece en el lomo",4),
("Piedra con filo", "destreza", 2, "No están equilibradas, pero clavan.",3),
("Chancla", "destreza", 2, "Una chancla para arrojarla contra los enemigos.",4),
("Chivata", "intelecto", 2, "Bastón que usan los viejos para espantar gamberros.",3),
("Cuchara", "intelecto", 2, "Una cuchara para apuntas hechizos o para comer sopa.",4),
("Tenedor", "fuerza", 3, "Tenedor para carnes, pincha bien en cualquier otra cosa.",5),
("Cuchillo para untar", "fuerza", 3, "Un cuchillo que no pincha pero corta, aunque no mucho",5),
("Tenedos", "destreza", 3,"Cubierto para pinchar con 2 puntas, es de tipo 2, es tene2",5),
("Boomerang", "destreza", 3, "Golpea y vuelve.",5),
("Rascaculos", "intelecto", 3, "Vara de cortalongtud que se usa para rascar dónde no te llegas.",5),
("Paleta de cocina", "intelecto", 3, "Puedes voltear la comida o lanzar hechizos.",5),
("Tijeras", "fuerza", 4, "Éstas pinchan y cortan.",6),
("Cuchillo jamonero", "fuerza", 4, "Para cortar jamón y enemigos.",6),
("Juego de cuchillos", "destreza", 4, "Colección de distintos tamaños para usar en la cocina, perfectos para lanzar.",6),
("Pedrolos", "destreza", 4, "Contundentes y azumban.",6),
("Cazo", "intelecto", 4, "Cuando no sacas del puchero, matas enemigos.",6),
("Vara de membrillo", "intelecto", 4, "Dobla e hinca en las costillas magicamente.",6),
("Espadita cortita", "fuerza", 5, "Arma clásica para pinchar y cortar.",7),
("Machete", "fuerza", 5, "Así le llamaban",7),
("Daga", "destreza", 5, "Meter cuchillo, sacar tripas.",7),
("Honda", "destreza", 5, "Arma para arrojar plomos con motor V y 150cv.",7),
("Garrote", "intelecto", 5, "Golpea en el lomo y lanza hechizos.",7),
("Vara de olivo", "intelecto", 5, "Una vara que varea.",7),
("Espada larga", "fuerza", 6, "Corta bien cualquier cosa mientras la mantengas afilada",8),
("Hacha", "fuerza", 6, "Parte cosas, los enemigos son cosas también.",9),
("Shuriken", "destreza", 6, "Estrella ninja para entendernos.",8),
("Estoque ES", "destreza", 6, "No es arrojadizo pero te puedes mover y pinchar rapido.",9),
("Baston", "intelecto", 6, "Atiza en la cabeza mientras estudias.",8),
("Varita de encina", "intelecto", 6, "Muy resistente y centenaria para lanzar magia.",9),
("Puño de kaio", "fuerza", 8, "Es la tecnica del Dios Kaio, te pone colorao.",10),
("MT 10", "destreza", 8, "Esta máquina técnica permite aprender el movimiento Poder Oculto.", 10),
("Pelotaca de fuego", "intelecto", 8, "Hechizo aprendid del libro del narrador de D&D.", 10);