insert into monstruo values
("Enredadera",1,1,2,1,2,"Es una planta que ha crecido sin control, tapara puertas y de vez en cuando sera un incordio."),
("Araña",1,2,1,2,1,"¡CUIDADO ARAÑA! siempre con esas patitas peluditas y esos ojos brillantes. Dan 'esgrima' literalmente, tiene un estoque."),
("Murciegalos",1,2,1,1,2,"Son murciegalos, no murcielagos. Son descendientes de murcianos y franceses."),
("Payasos",1,1,2,2,1,"Creeras que son divertidos, pero estudiaron un libro de chistes de Lepe, cuando cuentan chistes lo que te provoca es dolor agudo, como su humor."),
("Osolechuga",1,3,1,1,1,"Es una verdadera mutación simbiotica de una lechuga y un oso, fue un poquemon descartado por ser muy cutre, aun así es peligr'oso'."),
("Arpia",2,3,1,1,2,"Esta tia es muy chunga, es prima de la Jeny y la Vane."),
("Orco",2,2,1,1,3,"Es un orco generico, no le busques mas sentido."),
("Muerto Viviente",2,1,1,1,4,"Le encantan los huesitos y los tigretones."),
("Babosa Gigante",2,3,1,2,1,"Es pegajosa, huele mal, anda lento, no es fuerte, es un enemigo facil de vencer."),
("Lobo terrible",2,2,2,2,1,"Aulla muy mal, el pelo lo tiene descuidado y necesita gafas, su estilo es terrible."),
("Golem de masa de pan",3,2,2,2,2,"Su cabeza es un pan de cantos recien hecho. Esta muy rico."),
("Tortuga Ninja",3,4,1,1,2,"Son los primos gitanos de las verdaderas Tortugas Ninja, utiliza salchichones como nunchakus."),
("JavaException",3,1,1,4,2,"public class IllegalArgumentException extends RuntimeException. Thrown to indicate that a method has been passed an illegal or inappropriate argument. Since: JDK1.0"),
("Esfinge",3,1,1,1,5,"Gato sin pelo, da mucho repelus."),
("Crocopulpo",3,1,3,1,3,"Es un crocodilo con tentaculos, es una estrella del Hentai, tiene muchas extremidades."),
("Amazonas",4,3,1,1,5,"No se depilan, eso en Grecia no se lleva. Matan por kiki."),
("Zergling",4,2,2,2,4,"Solo cuesta cristales y salen dos por larva, para hacer un rush van muy bien."),
("Hipopogrifo",4,4,2,2,2,"Es un hipopotamo muy gordo con dos pequeñas alitas en la espalda, creo que utiliza celo para pegarselas."),
("Velociraptor",4,3,3,2,2,"Este dinosaurio es adicto a la velocidad, tiene un flamante BMW 320d."),
("Du Hamster",4,1,1,1,7,"Este hamster es fanatico de Ramstein, siempre canta Du Hast."),
("Vendedor de seguros",5,2,1,4,4,"No dejara de darte la brasa hasta que te venda un seguro de muerte con cremacion incluida."),
("Cruzcampo",5,3,3,3,2,"Meado de burra, tiene que estar muy fria y a punto de hielo, da mucho dolor de cabeza y una resaca mortal."),
("Brocoli",5,4,2,2,3,"Super Saiyan Legendario, rico en proteinas vegetales."),
("Biciclope",5,3,3,3,2,"Es una persona normal, tiene dos ojos."),
("Pichaku",5,1,4,4,2,"Es un pomekon de tipo electrico, tiene una bateria de 800mah, te deja tirado en cualquier momento, sobre todo cuando se acaba el botellon."),
("Troll",6,3,3,3,3,"Experto en foros, sabe utilizar el paint para hacerse sus memes y acosa a las tias que se encuentra en el lol."),
("Reloj Despertador",6,1,1,1,9,"BEEP! BEEP! BEEP! BEEP! BEEP! BEEP! BEEP! BEEP! BEEP! BEEP!"),
("Elemental de Pelos",6,2,3,4,3,"Magopelos lo creo, el pudo darle vida, practicamente por que es uno de los desarrolladores."),
("Mari-Conan",6,4,2,2,4,"Conan salio del armario y hay que apoyarle, paso de ser un simbolo de la virilidad para ser un icono de la lucha de los derechos homosexuales."),
("Jubilados",6,4,4,3,1,"El inserso cada vez se lo lleva a sitios mas extraños, estan de turismo por la mazmorra y te dejaran seco a base de pellizcos en los mofletes."),
("Javier Ramos",7,4,4,4,2,"Tiene su PC en la mazmorra y como nunca sale de ella estara jugando a algun juego, siempre tiene tabaco."),
("Surfista catolico",7,3,3,3,5,"Surfear una ola es tan gratificante para él como ir a misa el domingo."),
("Elemental de cuesco",7,3,3,4,2,"Es un elemental gaseoso que lo produjo un mago despues de comer mucha comida mexicana."),
("Salamanquesa",7,2,2,2,8,"Es la reina de las fiestas de un pequeño pueblo de Salamanca."),
("Dado Maldito",7,1,1,1,11,"Este dado siempre hara que tengas tiradas malas y te comas una pifia, nunca juegues con el al MERP."),
("Suspenso por un 4,5",8,4,4,4,3,"Esta desagradable situación es derivada de una tarde en la que tenias que haber estudiado, pero preferistes ver una pelicula."),
("Testigo de Jehova",8,3,3,3,6,"¿Hola, ha oido hablar de nuestro señor Yave?. Siempre tiene panfletos adoctrinantes."),
("El Bastardo",8,3,2,6,3,"Es hijo de un señorito español, actualmente trabaja en Genova y ocupa un cargo no electo en el gobierno."),
("Cani",8,4,4,1,6,"Vive en el parque de los patos, en vez de tirarte piedras se la fuma."),
("Medusa",8,1,1,1,12,"Es una criatura mitologica, dicen que mirarle a los ojos te petrifica, suerte que tiene buen cuerpo y no te fijas en esas cosas."),
("El señor obstuso",9,4,4,4,4,"El señor obstuso y del leru partido, que quiere la otra mitad para invitar a la peña de gratis y no pagar."),
("Fampiro",9,6,2,2,6,"Secuaz de Alejo I, el dictador que prohibio todas las expreciones de ocio y gobierna la mayor parte de Europa con una mezcla de dictadura y buenrollismo."),
("Gallo Colosal",9,3,3,3,7,"Un autentico gallo de 57kg, huyo de la casa de un americano un dia de acción de gracias y prometio vengarse del mundo."),
("Ninja con pandereta",9,5,5,3,3,"Podria haberte emboscado, pero oistes una pandereta y estabas en guardia, aun así sabe artes marciales."),
("Anti-Captcha",9,2,2,2,10,"'Completely Automated Public Turing Test', es un test controlado por una máquina, en logar de por un humano como en la prueba de Turing. Y ESTA ARMADO"),
("Dragon salchichonio",10,1,2,7,7,"No perseguirá a personajes de Nivel 5 o inferior. Mal rollo: te tuesta, te almuerza y te mata. Estas muerto."),
("El A'rock'allipsis",10,7,2,1,7,"I'm the lord of the wastelands, a modern day man of steel, I gather darkness to please me and I command you to kneel. Kiss - God of thunder"),
("Horse Luis",10,1,1,1,14,"Horse Luis es un fenomeno viral en twitter, nacio el 20 de Septiembre del 2014 y ha sido invitado a este juego. Su madre se lo ha permitido."),
("Rafalillo",10,1,6,7,3,"Siempre esta atento a todo movimiento, su humor tambien. Es un mago muy poderoso que se convirtio en elemental de llamas infernales, su enorme rabo en llamas es poderoso."),
("Enemigo pixelado",10,4,4,4,5,"Es una criatura de la antigüedad, antes de la alta definición. Su poder no se puede calcular o tardarias mucho, ya que fue diseñado en 8bits.")