/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Clase Principal para gestionar la interfaz grafica visual del juego
 *
 * @author Manuel David Villalba Escamilla
 * @author Victor Manuel Gonzalez Rodriguez
 * @author Alberto Gonzalez Rodriguez
 */
public class JFramePrincipal extends javax.swing.JFrame {

        
    /**
     * Constructor de la clase principal.
     * @param jPanel intancia del JPanel a mostrar en su interior.
     * @param url dirección de la imagen a mostrar en su fondo.
     */
    public JFramePrincipal(final JPanel jPanel, final String url) {

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowUI(jPanel, url);
            }
        });
    }

    /**
     * Constructor de la clase principal.
     * @param jPanel intancia del JPanel a mostrar en su interior.
     */
    public JFramePrincipal(final JPanel jPanel) {

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowUI(jPanel);
            }
        });
    }

    /**
     * Metodo para generar el panel del juego y mostrarlo con una imagen.
     * @param jPanel intancia del JPanel a mostrar en su interior.
     * @param url dirección de la imagen a mostrar en su fondo.
     */
    public void createAndShowUI(JPanel jPanel, String url) {
        try {
            frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600);
            Image image = Toolkit.getDefaultToolkit().getImage(url);
            frame.add(jPanel);
            frame.setTitle("Tontuna Dungeon");
            frame.setResizable(false);
            frame.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    
    /**
     * Metodo para generar el panel del juego y mostrarlo.
     * @param jPanel intancia del JPanel a mostrar en su interior.
     */
    public void createAndShowUI(JPanel jPanel) {
        try {
            frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600);
            frame.add(jPanel);
            frame.setTitle("Tontuna Dungeon");
            frame.setResizable(false);
            frame.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Metodo para ocultar el JFramePrincipal
     * @param bool true para mostrarlo, false para ocultarlo.
     */
    public void visible(boolean bool) {
        frame.setVisible(bool);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private JFrame frame;
}
